import = [
"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"
