{:user {:plugins [[lein-ring "0.9.6"]
                  [lein-ancient "0.6.7"]
                  [lein-figwheel "0.3.9"]
                  [lein-bikeshed "0.2.0"]
                  [lein-kibit "0.1.2"]
                  [lein-typed "0.3.5"]
                  [jonase/eastwood "0.2.1"]
                  [cider/cider-nrepl "0.10.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]
                       [acyclic/squiggly-clojure "0.1.4"]]}}
